# Generated by Django 4.2.13 on 2024-07-09 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('long_short', models.CharField(choices=[('long', 'long'), ('short', 'short')], default='long', max_length=5)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leverage', models.DecimalField(decimal_places=3, default=1, max_digits=5)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_trade_closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symbol', 'is_trade_closed')},
            },
        ),
    ]
