# Generated by Django 4.2.13 on 2024-07-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='leverage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
