# Generated by Django 4.2.13 on 2024-07-10 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0002_alter_trade_leverage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('user', 'created_at')},
        ),
    ]
