# Generated by Django 4.2.13 on 2024-07-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_trade_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
