# Generated by Django 4.2.13 on 2024-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_realizedprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizedprofit',
            name='daily_percentage_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='yesterday_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
