# Generated by Django 4.2.13 on 2024-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_realizedprofit_daily_percentage_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizedprofit',
            name='yesterday_total_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
