# Generated by Django 4.2.13 on 2024-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_realizedprofit_last_180_day_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizedprofit',
            name='daily_percentage_change',
        ),
        migrations.RemoveField(
            model_name='realizedprofit',
            name='last_180_day_profit',
        ),
        migrations.RemoveField(
            model_name='realizedprofit',
            name='last_30_day_profit',
        ),
        migrations.RemoveField(
            model_name='realizedprofit',
            name='last_90_day_profit',
        ),
        migrations.RemoveField(
            model_name='realizedprofit',
            name='today_pnl',
        ),
        migrations.RemoveField(
            model_name='realizedprofit',
            name='total_pnl',
        ),
        migrations.RemoveField(
            model_name='realizedprofit',
            name='yearly_profit',
        ),
        migrations.RemoveField(
            model_name='realizedprofit',
            name='yesterday_pnl',
        ),
        migrations.RemoveField(
            model_name='realizedprofit',
            name='yesterday_total_pnl',
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
