# Generated by Django 4.2.13 on 2024-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_remove_realizedprofit_daily_percentage_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizedprofit',
            name='daily_percentage_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='last_180_day_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='last_30_day_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='last_90_day_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='today_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='total_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='yearly_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='yesterday_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='realizedprofit',
            name='yesterday_total_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
