# Generated by Django 4.2.13 on 2024-07-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_realizedprofit_daily_percentage_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizedprofit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yearlyprofit',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalPnl',
        ),
        migrations.DeleteModel(
            name='RealizedProfit',
        ),
        migrations.DeleteModel(
            name='YearlyProfit',
        ),
    ]
