# Generated by Django 4.2.11 on 2024-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadcsv',
            name='exchange',
            field=models.CharField(choices=[('BloFin', 'BloFin'), ('OtherExchange', 'Other Exchange')], default='Blofin', max_length=100),
        ),
    ]
