# Generated by Django 4.2.11 on 2024-07-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_csv', '0002_alter_trade_pnl_alter_trade_pnl_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='avg_fill',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
