# Generated by Django 4.2.11 on 2024-07-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_csv', '0003_alter_tradeuploadcsv_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeuploadcsv',
            name='exchange',
            field=models.CharField(choices=[('BloFin', 'BloFin'), ('OtherExchange', 'Other Exchange')], default='', max_length=100),
        ),
    ]
