# Generated by Django 4.2.11 on 2024-07-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_csv', '0003_alter_trade_avg_fill_alter_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='avg_fill',
            field=models.CharField(max_length=50),
        ),
    ]
