# Generated by Django 4.2.11 on 2024-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_csv', '0005_alter_tradeuploadcsv_avg_fill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadcsv',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
