# Generated by Django 4.2.11 on 2024-07-31 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_csv', '0006_tradeuploadcsv_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeuploadcsv',
            old_name='status',
            new_name='trade_status',
        ),
        migrations.AlterField(
            model_name='tradeuploadcsv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_trades', to=settings.AUTH_USER_MODEL),
        ),
    ]
