# Generated by Django 4.2.11 on 2024-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
