# Generated by Django 4.2.11 on 2024-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0002_tradeuploadblofin_is_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeuploadblofin',
            name='is_matched',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='tradeuploadblofin',
            name='is_open',
            field=models.BooleanField(default=None),
        ),
    ]
