# Generated by Django 4.2.11 on 2024-08-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0003_alter_tradeuploadblofin_is_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='needs_price_update',
            field=models.BooleanField(default=False),
        ),
    ]
