# Generated by Django 4.2.11 on 2024-08-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0005_remove_tradeuploadblofin_needs_price_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
