# Generated by Django 4.2.11 on 2024-08-07 09:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0006_tradeuploadblofin_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='previous_net_pnl',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.0'), max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='previous_total_pnl_per_asset',
            field=models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.0'), max_digits=20, null=True),
        ),
    ]
