# Generated by Django 4.2.11 on 2024-08-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0007_tradeuploadblofin_previous_net_pnl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeuploadblofin',
            name='previous_net_pnl',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tradeuploadblofin',
            name='previous_total_pnl_per_asset',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
