# Generated by Django 4.2.11 on 2024-08-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0008_alter_tradeuploadblofin_previous_net_pnl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeuploadblofin',
            old_name='previous_net_pnl',
            new_name='realized_net_pnl',
        ),
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='unrealized_net_pnl',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
