# Generated by Django 4.2.11 on 2024-08-11 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades_upload_csv', '0009_rename_previous_net_pnl_tradeuploadblofin_realized_net_pnl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('total_quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('owner', 'asset')},
            },
        ),
    ]
