# Generated by Django 4.2.11 on 2024-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0010_livetrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='is_partially_matched',
            field=models.BooleanField(default=False),
        ),
    ]
