# Generated by Django 4.2.11 on 2024-08-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0011_tradeuploadblofin_is_partially_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeuploadblofin',
            name='original_filled',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
