# Generated by Django 4.2.11 on 2024-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0012_tradeuploadblofin_original_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrades',
            name='last_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
