# Generated by Django 4.2.11 on 2024-08-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0013_livetrades_last_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livetrades',
            name='last_processed',
        ),
        migrations.AddField(
            model_name='livetrades',
            name='trade_ids',
            field=models.JSONField(default=list),
        ),
    ]
