# Generated by Django 4.2.11 on 2024-08-12 18:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0014_remove_livetrades_last_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetrades',
            name='trade_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
