# Generated by Django 4.2.11 on 2024-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0015_alter_livetrades_trade_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetrades',
            name='trade_ids',
            field=models.TextField(default='[]'),
        ),
    ]
