# Generated by Django 4.2.11 on 2024-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0016_alter_livetrades_trade_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrades',
            name='avg_fill',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='livetrades',
            name='live_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='livetrades',
            name='live_pnl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='livetrades',
            name='live_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='livetrades',
            name='long_short',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
