# Generated by Django 4.2.11 on 2024-08-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0017_livetrades_avg_fill_livetrades_live_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livetrades',
            old_name='avg_fill',
            new_name='live_fill',
        ),
    ]
