# Generated by Django 4.2.11 on 2024-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0018_rename_avg_fill_livetrades_live_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrades',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
