# Generated by Django 4.2.11 on 2024-08-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0019_livetrades_is_live'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradeuploadblofin',
            unique_together={('underlying_asset', 'avg_fill', 'filled')},
        ),
    ]
