# Generated by Django 4.2.11 on 2024-08-16 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades_upload_csv', '0023_alter_tradeuploadblofin_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradeuploadblofin',
            unique_together={('owner', 'order_time', 'underlying_asset', 'avg_fill', 'filled', 'fee', 'pnl')},
        ),
    ]
