# Generated by Django 4.2.11 on 2024-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades_upload_csv', '0024_alter_tradeuploadblofin_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeuploadblofin',
            name='avg_fill',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
