# Generated by Django 4.2.11 on 2024-08-16 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades_upload_csv', '0025_alter_tradeuploadblofin_avg_fill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradeuploadblofin',
            unique_together={('owner', 'underlying_asset', 'avg_fill', 'filled', 'fee')},
        ),
    ]
