# Generated by Django 4.2.11 on 2024-08-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0002_rename_total_tradeuploadblofin_total_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeuploadblofin',
            old_name='filled',
            new_name='filled_quantity',
        ),
        migrations.RenameField(
            model_name='tradeuploadblofin',
            old_name='original_filled',
            new_name='original_filled_quantity',
        ),
        migrations.RemoveField(
            model_name='tradeuploadblofin',
            name='total_quantity',
        ),
    ]
