# Generated by Django 4.2.13 on 2024-07-19 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_profits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealizedProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('today_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yesterday_total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yesterday_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_percentage_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_30_day_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_90_day_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_180_day_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realized_profit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
